-- =====================================================
-- Migration: 009 - Fresh-Deployment Baseline & Schema Reconciliation
-- =====================================================
-- Description:
--   Makes `npm run migrate` on a pristine database produce a schema the
--   running code actually accepts, and reconciles the divergent schema
--   lineages that accumulated historically:
--     * init-db.sql        - orchestrator tables (projects keyed by project_id)
--     * create-minimal-*   - v1 API tables (VARCHAR ids, no users FKs)
--     * legacy 001-007     - aspirational UUID schema the code never matched
--     * runtime DDL        - users table self-created at boot
--   Legacy migrations 001-007 were retired to migrations/legacy/ — the
--   001→002 chain never completed on any database (002 conflicts with
--   001's api_keys), so no deployment depends on them running.
--
--   Everything here is idempotent and conditional, so it is safe on every
--   lineage: pristine DBs, init-db.sql compose deployments, runtime-
--   initialized DBs, and manually-applied legacy-migration DBs.
--
--   Identifier conventions (matching the code, not the legacy migrations):
--     * users.user_id / *_user_id columns: VARCHAR(64)  ('user_<ts>_<rand>')
--     * v1 entity ids (projects, conversations, ...): VARCHAR(255) (uuid strings)
--     * tenants ids: UUID (generated by the database, migration 008)
--     * No FKs to users: the users table shape varies by lineage, so the
--       application enforces that relationship.
-- Author: Zekka Framework Team
-- Date: 2026-07-19
-- Dependencies: 008_multi_tenancy.sql
-- =====================================================

BEGIN;

-- Serialize with the runtime schema initializer (user.repository.js uses the
-- same advisory-lock key) so a migration racing a booting app can't hit
-- catalog-level duplicate-key errors.
SELECT pg_advisory_xact_lock(727201);

-- =====================================================
-- 1. Canonical users table (same DDL as the runtime initializer)
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    email_verified BOOLEAN DEFAULT false,
    login_attempts INTEGER DEFAULT 0,
    failed_login_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE,
    last_login TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb,
    phone VARCHAR(32),
    telegram_id VARCHAR(64),
    username VARCHAR(255),
    auth_method VARCHAR(32) DEFAULT 'password',
    verified BOOLEAN DEFAULT false,
    password_expires_at TIMESTAMP WITH TIME ZONE,
    password_history JSONB DEFAULT '[]'::jsonb,
    reset_token TEXT,
    reset_token_expires_at TIMESTAMP WITH TIME ZONE,
    verification_token TEXT,
    verification_token_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Upgrade users tables from other lineages to the canonical superset.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS user_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS password_hash TEXT,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS login_attempts INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(32),
    ADD COLUMN IF NOT EXISTS telegram_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS username VARCHAR(255),
    ADD COLUMN IF NOT EXISTS auth_method VARCHAR(32) DEFAULT 'password',
    ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS password_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS password_history JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS reset_token TEXT,
    ADD COLUMN IF NOT EXISTS reset_token_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS verification_token TEXT,
    ADD COLUMN IF NOT EXISTS verification_token_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_user_id ON users(user_id);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);

-- =====================================================
-- 2. Disambiguate the orchestrator tables
-- =====================================================
-- The orchestrator historically used tables named `projects` and `tasks`
-- (from init-db.sql) that collide with the v1 API's tables of the same
-- names. The orchestrator now uses orchestration_* names; rename existing
-- orchestrator-shape tables so their data is preserved.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'projects'
                 AND column_name = 'project_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables
                       WHERE table_schema = 'public'
                         AND table_name = 'orchestration_projects') THEN
        ALTER TABLE projects RENAME TO orchestration_projects;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'tasks'
                 AND column_name = 'task_id')
       AND EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public' AND table_name = 'tasks'
                     AND column_name = 'stage')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables
                       WHERE table_schema = 'public'
                         AND table_name = 'orchestration_tasks') THEN
        ALTER TABLE tasks RENAME TO orchestration_tasks;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS orchestration_projects (
    id SERIAL PRIMARY KEY,
    project_id VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',
    story_points INTEGER,
    budget_daily DECIMAL(10, 2),
    budget_monthly DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orchestration_tasks (
    id SERIAL PRIMARY KEY,
    task_id VARCHAR(255) UNIQUE NOT NULL,
    project_id VARCHAR(255) REFERENCES orchestration_projects(project_id),
    stage INTEGER NOT NULL,
    agent_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'pending',
    input_data JSONB,
    output_data JSONB,
    error_message TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orch_projects_project_id ON orchestration_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_orch_tasks_task_id ON orchestration_tasks(task_id);
CREATE INDEX IF NOT EXISTS idx_orch_tasks_project_id ON orchestration_tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_orch_tasks_status ON orchestration_tasks(status);

CREATE TABLE IF NOT EXISTS cost_tracking (
    id SERIAL PRIMARY KEY,
    project_id VARCHAR(255),
    task_id VARCHAR(255),
    agent_name VARCHAR(255),
    model_used VARCHAR(255),
    tokens_input INTEGER,
    tokens_output INTEGER,
    cost_usd DECIMAL(12, 6),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cost_tracking_project_id ON cost_tracking(project_id);
CREATE INDEX IF NOT EXISTS idx_cost_tracking_timestamp ON cost_tracking(timestamp);

-- =====================================================
-- 3. Repair uuid-lineage v1 tables (legacy 003/004, applied manually)
-- =====================================================
-- The v1 API code uses VARCHAR ids; uuid-shaped tables from the legacy
-- migrations never accepted the code's inserts, so they can only be empty.
-- Empty uuid-shaped tables are dropped and recreated below; non-empty ones
-- (hand-inserted data) are left for operator reconciliation.
DO $$
DECLARE
    t TEXT;
    id_type TEXT;
    row_count BIGINT;
BEGIN
    FOREACH t IN ARRAY ARRAY['message_reactions', 'messages', 'conversations',
                             'sources', 'project_members', 'projects'] LOOP
        SELECT data_type INTO id_type
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = t AND column_name = 'id';

        IF id_type = 'uuid' THEN
            EXECUTE format('SELECT COUNT(*) FROM %I', t) INTO row_count;
            IF row_count = 0 THEN
                EXECUTE format('DROP TABLE %I CASCADE', t);
                RAISE NOTICE 'Dropped empty uuid-lineage table % for recreation', t;
            ELSE
                RAISE NOTICE 'Table % has uuid ids and % rows — left untouched, manual reconciliation required', t, row_count;
            END IF;
        END IF;
    END LOOP;
END
$$;

-- =====================================================
-- 4. v1 API tables (VARCHAR ids — the shapes the code works against)
-- =====================================================
CREATE TABLE IF NOT EXISTS projects (
    id VARCHAR(255) PRIMARY KEY,
    owner_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS project_type VARCHAR(100) DEFAULT 'web-application',
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_projects_owner_id ON projects(owner_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS project_members (
    id VARCHAR(255) PRIMARY KEY,
    project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id VARCHAR(64) NOT NULL,
    role VARCHAR(50) DEFAULT 'viewer',
    added_by VARCHAR(64),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_members_project_id ON project_members(project_id);
CREATE INDEX IF NOT EXISTS idx_project_members_user_id ON project_members(user_id);

CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(255) PRIMARY KEY,
    project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS message_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_conversations_project_id ON conversations(project_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations(status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS messages (
    id VARCHAR(255) PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id VARCHAR(64),
    content TEXT NOT NULL,
    role VARCHAR(50) DEFAULT 'user',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS parent_message_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS model VARCHAR(100),
    ADD COLUMN IF NOT EXISTS tokens_used INTEGER;

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);

CREATE TABLE IF NOT EXISTS message_reactions (
    id VARCHAR(255) PRIMARY KEY,
    message_id VARCHAR(255) NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id VARCHAR(64) NOT NULL,
    reaction VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(message_id, user_id, reaction)
);

CREATE INDEX IF NOT EXISTS idx_message_reactions_message_id ON message_reactions(message_id);

CREATE TABLE IF NOT EXISTS sources (
    id VARCHAR(255) PRIMARY KEY,
    project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    url TEXT,
    content TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE sources
    ADD COLUMN IF NOT EXISTS file_size BIGINT,
    ADD COLUMN IF NOT EXISTS mime_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';

CREATE INDEX IF NOT EXISTS idx_sources_project_id ON sources(project_id);
CREATE INDEX IF NOT EXISTS idx_sources_user_id ON sources(user_id);

-- Tenant scoping (008's conditional ALTER is a no-op on fresh DBs because
-- projects did not exist yet at that point in the chain).
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_projects_tenant_id ON projects(tenant_id) WHERE tenant_id IS NOT NULL;

-- =====================================================
-- 5. Preferences (from legacy 003, user_id → VARCHAR, no users FK)
-- =====================================================
CREATE TABLE IF NOT EXISTS user_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(64) NOT NULL,
    category VARCHAR(100) NOT NULL,
    key VARCHAR(255) NOT NULL,
    value JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, category, key)
);

CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON user_preferences(user_id);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(64) NOT NULL UNIQUE,
    email_enabled BOOLEAN DEFAULT TRUE,
    push_enabled BOOLEAN DEFAULT TRUE,
    sms_enabled BOOLEAN DEFAULT FALSE,
    in_app_enabled BOOLEAN DEFAULT TRUE,
    project_updates BOOLEAN DEFAULT TRUE,
    agent_notifications BOOLEAN DEFAULT TRUE,
    system_alerts BOOLEAN DEFAULT TRUE,
    marketing_emails BOOLEAN DEFAULT FALSE,
    digest_frequency VARCHAR(50) DEFAULT 'daily',
    quiet_hours_enabled BOOLEAN DEFAULT FALSE,
    quiet_hours_start TIME,
    quiet_hours_end TIME,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_preferences_user_id ON notification_preferences(user_id);

-- =====================================================
-- 6. Security/audit tables (from legacy 002, user ids → VARCHAR, no FK)
-- =====================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(64),
    username VARCHAR(255),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id VARCHAR(255),
    method VARCHAR(10),
    endpoint VARCHAR(500),
    ip_address INET,
    user_agent TEXT,
    session_id VARCHAR(255),
    api_key_id VARCHAR(255),
    request_body JSONB,
    response_status INTEGER,
    response_body JSONB,
    success BOOLEAN NOT NULL DEFAULT true,
    error_message TEXT,
    error_code VARCHAR(50),
    duration_ms INTEGER,
    is_suspicious BOOLEAN DEFAULT false,
    risk_level VARCHAR(20) DEFAULT 'low',
    country_code VARCHAR(8),
    city VARCHAR(255),
    retention_days INTEGER
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

CREATE TABLE IF NOT EXISTS password_history (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    password_hash TEXT NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by VARCHAR(64),
    change_reason VARCHAR(50),
    ip_address INET
);

CREATE INDEX IF NOT EXISTS idx_password_history_user ON password_history(user_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS encryption_keys (
    id SERIAL PRIMARY KEY,
    key_id VARCHAR(100) UNIQUE NOT NULL,
    key_type VARCHAR(50) NOT NULL,
    key_value TEXT NOT NULL,
    key_hash VARCHAR(255) NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    key_size INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    rotated_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    is_primary BOOLEAN DEFAULT false,
    created_by VARCHAR(64),
    rotation_reason VARCHAR(255),
    rotation_policy VARCHAR(50) DEFAULT '90_days',
    usage_count BIGINT DEFAULT 0,
    last_used_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_encryption_keys_key_id ON encryption_keys(key_id);

-- =====================================================
-- 7. Activity/analytics tables (used by code, never had DDL anywhere)
-- =====================================================
CREATE TABLE IF NOT EXISTS agent_activities (
    id BIGSERIAL PRIMARY KEY,
    agent_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255),
    action VARCHAR(255) NOT NULL,
    metadata JSONB DEFAULT '{}',
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_activities_agent_id ON agent_activities(agent_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_agent_activities_project_id ON agent_activities(project_id);

CREATE TABLE IF NOT EXISTS token_usage (
    id BIGSERIAL PRIMARY KEY,
    conversation_id VARCHAR(255),
    project_id VARCHAR(255),
    agent_id VARCHAR(255),
    model VARCHAR(100),
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER DEFAULT 0,
    cost DECIMAL(12, 6) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_token_usage_conversation_id ON token_usage(conversation_id);
CREATE INDEX IF NOT EXISTS idx_token_usage_created_at ON token_usage(created_at);

-- =====================================================
-- 8. Context-bus persistence tables (from init-db.sql)
-- =====================================================
CREATE TABLE IF NOT EXISTS agent_states (
    id SERIAL PRIMARY KEY,
    task_id VARCHAR(255) REFERENCES orchestration_tasks(task_id),
    agent_name VARCHAR(255),
    state JSONB,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file_locks (
    id SERIAL PRIMARY KEY,
    task_id VARCHAR(255) REFERENCES orchestration_tasks(task_id),
    file_path TEXT NOT NULL,
    agent_name VARCHAR(255),
    locked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conflicts (
    id SERIAL PRIMARY KEY,
    conflict_id VARCHAR(255) UNIQUE NOT NULL,
    task_id VARCHAR(255) REFERENCES orchestration_tasks(task_id),
    description TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    resolution JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP
);

-- =====================================================
-- updated_at triggers (function defined idempotently in 008)
-- =====================================================
DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_conversations_updated_at ON conversations;
CREATE TRIGGER update_conversations_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMIT;
